spring:
  datasource:
    url: jdbc:postgresql://localhost:6330/literalura
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  application:
    name: LiterAlura-Catalog
